/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booktracker.view;

import booktracker.classes.BookCategory;
import booktracker.service.BookCategoryService;
import booktracker.util.Response;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author haris
 */
public class BookCategoryFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookCategoryFrame.class.getName());
    private final BookCategoryService service = new BookCategoryService();

    /**
     * Creates new form BookCategoryFrame
     */
    public BookCategoryFrame() {
        initComponents();

        this.mapCategoriesToTable(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootCatPanel = new javax.swing.JPanel();
        backCatBtn = new javax.swing.JButton();
        deleteCatActionBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        editCatActionBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookCategoryUITable = new javax.swing.JTable();
        addCatActionBtn = new javax.swing.JButton();
        searchCatField = new javax.swing.JTextField();
        searchCatActionBtn = new javax.swing.JButton();
        titleCatLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootCatPanel.setBackground(new java.awt.Color(232, 255, 215));

        backCatBtn.setBackground(new java.awt.Color(229, 229, 229));
        backCatBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        backCatBtn.setText("Back");
        backCatBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        backCatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCatBtnActionPerformed(evt);
            }
        });

        deleteCatActionBtn.setBackground(new java.awt.Color(220, 38, 38));
        deleteCatActionBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        deleteCatActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteCatActionBtn.setText("Delete");
        deleteCatActionBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        deleteCatActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCatActionBtnActionPerformed(evt);
            }
        });

        resetBtn.setBackground(new java.awt.Color(229, 229, 229));
        resetBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        editCatActionBtn.setBackground(new java.awt.Color(250, 204, 21));
        editCatActionBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        editCatActionBtn.setText("Edit");
        editCatActionBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        editCatActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCatActionBtnActionPerformed(evt);
            }
        });

        bookCategoryUITable.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        bookCategoryUITable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Category Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bookCategoryUITable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(bookCategoryUITable);

        addCatActionBtn.setBackground(new java.awt.Color(37, 99, 235));
        addCatActionBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        addCatActionBtn.setForeground(new java.awt.Color(255, 255, 255));
        addCatActionBtn.setText("Add");
        addCatActionBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        addCatActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCatActionBtnActionPerformed(evt);
            }
        });

        searchCatField.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        searchCatField.setPreferredSize(new java.awt.Dimension(100, 30));

        searchCatActionBtn.setBackground(new java.awt.Color(229, 229, 229));
        searchCatActionBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        searchCatActionBtn.setText("Search");
        searchCatActionBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        searchCatActionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCatActionBtnActionPerformed(evt);
            }
        });

        titleCatLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        titleCatLabel.setText("Manage Category");

        javax.swing.GroupLayout rootCatPanelLayout = new javax.swing.GroupLayout(rootCatPanel);
        rootCatPanel.setLayout(rootCatPanelLayout);
        rootCatPanelLayout.setHorizontalGroup(
            rootCatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootCatPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(rootCatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootCatPanelLayout.createSequentialGroup()
                        .addComponent(titleCatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rootCatPanelLayout.createSequentialGroup()
                        .addGroup(rootCatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rootCatPanelLayout.createSequentialGroup()
                                .addComponent(searchCatField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addGroup(rootCatPanelLayout.createSequentialGroup()
                                .addComponent(editCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backCatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
        );
        rootCatPanelLayout.setVerticalGroup(
            rootCatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootCatPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(titleCatLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(rootCatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootCatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backCatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCatActionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootCatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootCatPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mapCategoriesToTable(String query) {
        // Method to map categories to the table (to be implemented)
        Response<List<BookCategory>> response = service.getAll(query);

        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }

        List<BookCategory> categories = response.getData();
        DefaultTableModel model = (DefaultTableModel) bookCategoryUITable.getModel();
        model.setNumRows(0);
        for (BookCategory category : categories) {
            Object[] rowData = {category.getId(), category.getName()};
            model.addRow(rowData);
        }
    }

    private void backCatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCatBtnActionPerformed
        // TODO add your handling code here:
        new MainFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_backCatBtnActionPerformed

    private void addCatActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCatActionBtnActionPerformed
        // TODO add your handling code here:
        new BookCategoryFormFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_addCatActionBtnActionPerformed

    private void editCatActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCatActionBtnActionPerformed
        // TODO add your handling code here:
        int row = bookCategoryUITable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a category to edit.");
            return;
        }

        new BookCategoryFormFrame(Integer.parseInt(bookCategoryUITable.getValueAt(row, 0).toString())).setVisible(true);
        dispose();
    }//GEN-LAST:event_editCatActionBtnActionPerformed

    private void deleteCatActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCatActionBtnActionPerformed
        // TODO add your handling code here:
        int row = bookCategoryUITable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Please select a category to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the selected category?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        Response<Void> response = service.delete((Integer) bookCategoryUITable.getValueAt(row, 0));
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, response.getMessage());
            return;
        }

        ((DefaultTableModel) bookCategoryUITable.getModel()).removeRow(row);
        JOptionPane.showMessageDialog(this, response.getMessage());
    }//GEN-LAST:event_deleteCatActionBtnActionPerformed

    private void searchCatActionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCatActionBtnActionPerformed
        // TODO add your handling code here:
        String query = searchCatField.getText().trim();

        if (query.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a search query.");
            return;
        }

        this.mapCategoriesToTable(query);
    }//GEN-LAST:event_searchCatActionBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        this.mapCategoriesToTable(null);
        searchCatField.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatLaf Light (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlafLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookCategoryFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCatActionBtn;
    private javax.swing.JButton backCatBtn;
    private javax.swing.JTable bookCategoryUITable;
    private javax.swing.JButton deleteCatActionBtn;
    private javax.swing.JButton editCatActionBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rootCatPanel;
    private javax.swing.JButton searchCatActionBtn;
    private javax.swing.JTextField searchCatField;
    private javax.swing.JLabel titleCatLabel;
    // End of variables declaration//GEN-END:variables
}
