/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package booktracker.view;

import booktracker.classes.Book;
import booktracker.classes.BookCategory;
import booktracker.classes.Status;
import booktracker.component.ComboBoxItem;
import booktracker.service.BookCategoryService;
import booktracker.service.BookService;
import booktracker.util.Response;

import javax.swing.*;
import java.util.List;
import java.time.LocalDate;

/**
 *
 * @author haris
 */
public class BookFormFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookFormFrame.class.getName());
    private final BookCategoryService bookCategoryService = new BookCategoryService();
    private final BookService bookService = new BookService();
    private int objectId = -1;
    private boolean isEdit = false;

    /**
     * Creates new form BookFormFrame
     */
    public BookFormFrame() {
        initComponents();

        populateCategoryComboBox();
        populateStatusComboBox();
    }

    public BookFormFrame(int objectId) {
        this.objectId = objectId;
        this.isEdit = true;

        initComponents();

        populateCategoryComboBox();
        populateStatusComboBox();
        initiateFieldForUpdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        bookTitleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        categoryLabel = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox<>();
        startDateLabel = new javax.swing.JLabel();
        startDateField = new javax.swing.JTextField();
        endDateLabel = new javax.swing.JLabel();
        endDateField = new javax.swing.JTextField();
        currentPageLabel = new javax.swing.JLabel();
        currentPageField = new javax.swing.JTextField();
        totalPagesLabel = new javax.swing.JLabel();
        totalPagesField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        manageBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(232, 255, 215));

        titleLabel.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        titleLabel.setText("Manage Book");

        bookTitleLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        bookTitleLabel.setText("Title");

        titleField.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        titleField.setPreferredSize(new java.awt.Dimension(100, 30));

        categoryLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        categoryLabel.setText("Category");

        categoryComboBox.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        categoryComboBox.setMinimumSize(new java.awt.Dimension(90, 30));

        startDateLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        startDateLabel.setText("Start Date");

        startDateField.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        startDateField.setPreferredSize(new java.awt.Dimension(100, 30));

        endDateLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        endDateLabel.setText("End Date");

        endDateField.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        endDateField.setPreferredSize(new java.awt.Dimension(100, 30));

        currentPageLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        currentPageLabel.setText("Current Page");

        currentPageField.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        currentPageField.setPreferredSize(new java.awt.Dimension(100, 30));

        totalPagesLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        totalPagesLabel.setText("Total Pages");

        totalPagesField.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        totalPagesField.setPreferredSize(new java.awt.Dimension(100, 30));

        statusLabel.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        statusLabel.setText("Status");

        statusComboBox.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        statusComboBox.setMinimumSize(new java.awt.Dimension(90, 30));

        manageBtn.setBackground(new java.awt.Color(37, 99, 235));
        manageBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        manageBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageBtn.setText(this.isEdit ? "Update" : "Add");
        manageBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(229, 229, 229));
        backBtn.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        backBtn.setText("Cancel");
        backBtn.setPreferredSize(new java.awt.Dimension(90, 30));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
                rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rootPanelLayout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(268, 293, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rootPanelLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(currentPageLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(currentPageField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                        .addComponent(statusLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(statusComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                                .addGap(73, 73, 73)
                                                                                .addComponent(totalPagesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(totalPagesField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                                .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                                                                .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(bookTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(titleField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                                        .addComponent(startDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                                .addGap(73, 73, 73)
                                                                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                        .addComponent(endDateLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                                                        .addComponent(categoryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap(93, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
                rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(titleLabel)
                                .addGap(21, 21, 21)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bookTitleLabel)
                                        .addComponent(categoryLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                                .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)))
                                .addGap(26, 26, 26)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startDateLabel)
                                        .addComponent(endDateLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(currentPageLabel)
                                        .addComponent(totalPagesLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(currentPageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalPagesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(statusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backAction() {
        new BookFrame().setVisible(true);
        dispose();
    }

    private void clearField() {
        titleField.setText("");
        startDateField.setText("");
        endDateField.setText("");
        currentPageField.setText("");
        totalPagesField.setText("");
    }

    private Book validateBook() {
        try {
            String title = titleField.getText().trim();
            ComboBoxItem selectedCategoryItem = (ComboBoxItem) categoryComboBox.getSelectedItem();
            String startDateStr = startDateField.getText().trim();
            String endDateStr = isEdit ? endDateField.getText().trim() : "";
            String currentPageStr = currentPageField.getText().trim();
            String totalPagesStr = totalPagesField.getText().trim();
            ComboBoxItem selectedStatusItem = (ComboBoxItem) statusComboBox.getSelectedItem();

            if (title.isEmpty() || selectedCategoryItem == null || startDateStr.isEmpty() || currentPageStr.isEmpty() || totalPagesStr.isEmpty() || selectedStatusItem == null) {
                throw new IllegalArgumentException("Please fill in all fields.");
            }

            if (isEdit && endDateStr.isEmpty()) {
                throw new IllegalArgumentException("Please fill in all fields.");
            }

            BookCategory category = new BookCategory((int) selectedCategoryItem.getValue(), selectedCategoryItem.toString());
            LocalDate startDate = LocalDate.parse(startDateStr);
            LocalDate endDate = isEdit ? LocalDate.parse(endDateStr) : null;
            int currentPage = Integer.parseInt(currentPageStr);
            int totalPages = Integer.parseInt(totalPagesStr);
            Status selectedStatus = (Status) selectedStatusItem.getValue();

            if (startDate.isAfter(endDate)) {
                throw new IllegalArgumentException("Start date cannot be after end date.");
            }

            return new Book(this.objectId, title, category, startDate, endDate, currentPage, totalPages, selectedStatus);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Current Page and Total Pages must be valid integers.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return null;
    }

    private void manageAction() {
        try {
            Book book = validateBook();

            if (book == null) {
                return;
            }

            Response<Void> response = isEdit ? bookService.update(book) : bookService.create(book.getTitle(), book.getCategory(), book.getStartDate(), book.getCurrentPage(), book.getTotalPages());
            if (!response.isSuccess()) {
                JOptionPane.showMessageDialog(this, "Failed to " + (isEdit ? "update" : "create") + " book: " + response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            JOptionPane.showMessageDialog(this, "Book " + (isEdit ? "updated" : "created") + " successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            backAction();
            clearField();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
        manageAction();
    }//GEN-LAST:event_manageBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf Light look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If FlatLaf Light (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookFormFrame().setVisible(true));
    }

    private void populateCategoryComboBox() {
        Response<List<BookCategory>> response = bookCategoryService.getAll(null);
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, "Failed to load categories: " + response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        List<BookCategory> categories = response.getData();
        int index = 0;
        for (int i = 0; i < categories.size(); i++) {
            BookCategory category = categories.get(i);
            ComboBoxItem item = new ComboBoxItem(category.getName(), category.getId());
            categoryComboBox.addItem(item);
            if (isEdit && category.getId() == objectId) {
                index = i;
            }
        }

        if (isEdit) {
            categoryComboBox.setSelectedIndex(index);
        }
    }

    private void populateStatusComboBox() {
        int index = 0;
        Status[] statuses = Status.values();
        for (int i = 0; i < statuses.length; i++) {
            Status status = statuses[i];
            ComboBoxItem item = new ComboBoxItem(status.name().replace("_", " "), status);
            statusComboBox.addItem(item);
            if (isEdit && status == bookService.getById(objectId).getData().getStatus()) {
                index = i;
            }
        }

        if (isEdit) {
            statusComboBox.setSelectedIndex(index);
        }
    }

    private void initiateFieldForUpdate() {
        Response<Book> response = bookService.getById(objectId);
        if (!response.isSuccess()) {
            JOptionPane.showMessageDialog(this, "Failed to load book: " + response.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Book book = response.getData();
        titleField.setText(book.getTitle());
        startDateField.setText(book.getStartDate().toString());
        endDateField.setText(book.getEndDate() != null ? book.getEndDate().toString() : "");
        currentPageField.setText(String.valueOf(book.getCurrentPage()));
        totalPagesField.setText(String.valueOf(book.getTotalPages()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bookTitleLabel;
    private javax.swing.JComboBox<ComboBoxItem> categoryComboBox;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JTextField currentPageField;
    private javax.swing.JLabel currentPageLabel;
    private javax.swing.JTextField endDateField;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JButton manageBtn;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JTextField startDateField;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JComboBox<ComboBoxItem> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField totalPagesField;
    private javax.swing.JLabel totalPagesLabel;
    // End of variables declaration//GEN-END:variables
}
