/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.view;

/**
 *
 * @author haris
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculatorFrame.class.getName());

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        outputField = new javax.swing.JTextField();
        decimalPad = new javax.swing.JButton();
        zeroPad = new javax.swing.JButton();
        equalPad = new javax.swing.JButton();
        onePad = new javax.swing.JButton();
        twoPad = new javax.swing.JButton();
        threePad = new javax.swing.JButton();
        fourPad = new javax.swing.JButton();
        fivePad = new javax.swing.JButton();
        sixPad = new javax.swing.JButton();
        sevenPad = new javax.swing.JButton();
        eightPad = new javax.swing.JButton();
        ninePad = new javax.swing.JButton();
        deletePad = new javax.swing.JButton();
        allClearPad = new javax.swing.JButton();
        multiplyPad = new javax.swing.JButton();
        dividePad = new javax.swing.JButton();
        plusPad = new javax.swing.JButton();
        minusPad = new javax.swing.JButton();
        leftBracesPad = new javax.swing.JButton();
        rightBracesPad = new javax.swing.JButton();
        sinPad = new javax.swing.JButton();
        cosPad = new javax.swing.JButton();
        tanPad = new javax.swing.JButton();
        factPad = new javax.swing.JButton();
        permutationPad = new javax.swing.JButton();
        combinationPad = new javax.swing.JButton();
        eulerPad = new javax.swing.JButton();
        logPad = new javax.swing.JButton();
        cbrtPad = new javax.swing.JButton();
        modPad = new javax.swing.JButton();
        expPad = new javax.swing.JButton();
        sqrtPad = new javax.swing.JButton();
        copyrightLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBackground(new java.awt.Color(250, 250, 250));

        inputField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputField.setEnabled(false);

        outputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outputField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        outputField.setEnabled(false);

        decimalPad.setText(".");
        decimalPad.setPreferredSize(new java.awt.Dimension(50, 50));
        decimalPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalPadActionPerformed(evt);
            }
        });

        zeroPad.setText("0");
        zeroPad.setPreferredSize(new java.awt.Dimension(50, 50));
        zeroPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroPadActionPerformed(evt);
            }
        });

        equalPad.setText("=");
        equalPad.setPreferredSize(new java.awt.Dimension(50, 50));
        equalPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalPadActionPerformed(evt);
            }
        });

        onePad.setText("1");
        onePad.setPreferredSize(new java.awt.Dimension(50, 50));
        onePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePadActionPerformed(evt);
            }
        });

        twoPad.setText("2");
        twoPad.setPreferredSize(new java.awt.Dimension(50, 50));
        twoPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPadActionPerformed(evt);
            }
        });

        threePad.setText("3");
        threePad.setPreferredSize(new java.awt.Dimension(50, 50));
        threePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePadActionPerformed(evt);
            }
        });

        fourPad.setText("4");
        fourPad.setPreferredSize(new java.awt.Dimension(50, 50));
        fourPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourPadActionPerformed(evt);
            }
        });

        fivePad.setText("5");
        fivePad.setPreferredSize(new java.awt.Dimension(50, 50));
        fivePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivePadActionPerformed(evt);
            }
        });

        sixPad.setText("6");
        sixPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sixPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixPadActionPerformed(evt);
            }
        });

        sevenPad.setText("7");
        sevenPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sevenPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenPadActionPerformed(evt);
            }
        });

        eightPad.setText("8");
        eightPad.setPreferredSize(new java.awt.Dimension(50, 50));
        eightPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightPadActionPerformed(evt);
            }
        });

        ninePad.setText("9");
        ninePad.setPreferredSize(new java.awt.Dimension(50, 50));
        ninePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninePadActionPerformed(evt);
            }
        });

        deletePad.setText("D");
        deletePad.setPreferredSize(new java.awt.Dimension(50, 50));
        deletePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePadActionPerformed(evt);
            }
        });

        allClearPad.setText("AC");
        allClearPad.setPreferredSize(new java.awt.Dimension(50, 50));
        allClearPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearPadActionPerformed(evt);
            }
        });

        multiplyPad.setText("*");
        multiplyPad.setPreferredSize(new java.awt.Dimension(50, 50));
        multiplyPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyPadActionPerformed(evt);
            }
        });

        dividePad.setText("/");
        dividePad.setPreferredSize(new java.awt.Dimension(50, 50));
        dividePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividePadActionPerformed(evt);
            }
        });

        plusPad.setText("+");
        plusPad.setPreferredSize(new java.awt.Dimension(50, 50));
        plusPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusPadActionPerformed(evt);
            }
        });

        minusPad.setText("-");
        minusPad.setPreferredSize(new java.awt.Dimension(50, 50));
        minusPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusPadActionPerformed(evt);
            }
        });

        leftBracesPad.setText("(");
        leftBracesPad.setPreferredSize(new java.awt.Dimension(50, 50));
        leftBracesPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBracesPadActionPerformed(evt);
            }
        });

        rightBracesPad.setText(")");
        rightBracesPad.setPreferredSize(new java.awt.Dimension(50, 50));
        rightBracesPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBracesPadActionPerformed(evt);
            }
        });

        sinPad.setText("sin");
        sinPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sinPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinPadActionPerformed(evt);
            }
        });

        cosPad.setText("cos");
        cosPad.setPreferredSize(new java.awt.Dimension(50, 50));
        cosPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosPadActionPerformed(evt);
            }
        });

        tanPad.setText("tan");
        tanPad.setPreferredSize(new java.awt.Dimension(50, 50));
        tanPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanPadActionPerformed(evt);
            }
        });

        factPad.setText("n!");
        factPad.setPreferredSize(new java.awt.Dimension(50, 50));
        factPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factPadActionPerformed(evt);
            }
        });

        permutationPad.setText("P()");
        permutationPad.setPreferredSize(new java.awt.Dimension(50, 50));
        permutationPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permutationPadActionPerformed(evt);
            }
        });

        combinationPad.setText("C()");
        combinationPad.setPreferredSize(new java.awt.Dimension(50, 50));
        combinationPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combinationPadActionPerformed(evt);
            }
        });

        eulerPad.setText("exp");
        eulerPad.setPreferredSize(new java.awt.Dimension(50, 50));
        eulerPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulerPadActionPerformed(evt);
            }
        });

        logPad.setText("log");
        logPad.setPreferredSize(new java.awt.Dimension(50, 50));
        logPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPadActionPerformed(evt);
            }
        });

        cbrtPad.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbrtPad.setText("cbrt");
        cbrtPad.setPreferredSize(new java.awt.Dimension(50, 50));
        cbrtPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrtPadActionPerformed(evt);
            }
        });

        modPad.setText("%");
        modPad.setPreferredSize(new java.awt.Dimension(50, 50));
        modPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPadActionPerformed(evt);
            }
        });

        expPad.setText("^");
        expPad.setPreferredSize(new java.awt.Dimension(50, 50));
        expPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expPadActionPerformed(evt);
            }
        });

        sqrtPad.setText("sqrt");
        sqrtPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sqrtPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtPadActionPerformed(evt);
            }
        });

        copyrightLabel.setText("Copyright");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fourPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sevenPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rootPanelLayout.createSequentialGroup()
                                        .addComponent(eightPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ninePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rootPanelLayout.createSequentialGroup()
                                        .addComponent(fivePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sixPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(onePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(twoPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(threePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(decimalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zeroPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(equalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(deletePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(allClearPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(multiplyPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dividePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(plusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(minusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(leftBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rightBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(modPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sqrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(eulerPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(logPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(factPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(permutationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combinationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addComponent(sinPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cosPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tanPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(outputField)
                    .addComponent(inputField)
                    .addComponent(copyrightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevenPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ninePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allClearPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cosPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fourPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fivePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sixPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dividePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permutationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combinationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eulerPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(decimalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeroPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(copyrightLabel)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decimalPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("."));
    }//GEN-LAST:event_decimalPadActionPerformed

    private void zeroPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("0"));
    }//GEN-LAST:event_zeroPadActionPerformed

    private void equalPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalPadActionPerformed
        // TODO add your handling code here:
        // TODO call service
    }//GEN-LAST:event_equalPadActionPerformed

    private void onePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onePadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("1"));
    }//GEN-LAST:event_onePadActionPerformed

    private void twoPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("2"));
    }//GEN-LAST:event_twoPadActionPerformed

    private void threePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("3"));
    }//GEN-LAST:event_threePadActionPerformed

    private void fourPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("4"));
    }//GEN-LAST:event_fourPadActionPerformed

    private void fivePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivePadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("5"));
    }//GEN-LAST:event_fivePadActionPerformed

    private void sixPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("6"));
    }//GEN-LAST:event_sixPadActionPerformed

    private void sevenPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("7"));
    }//GEN-LAST:event_sevenPadActionPerformed

    private void eightPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("8"));
    }//GEN-LAST:event_eightPadActionPerformed

    private void ninePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninePadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("9"));
    }//GEN-LAST:event_ninePadActionPerformed

    private void deletePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePadActionPerformed
        // TODO add your handling code here:
        String currentText = inputField.getText();
        if (!currentText.isEmpty()) {
            inputField.setText(currentText.substring(0, currentText.length() - 1));
        }
    }//GEN-LAST:event_deletePadActionPerformed

    private void allClearPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClearPadActionPerformed
        // TODO add your handling code here:
        inputField.setText("");
        outputField.setText("");
    }//GEN-LAST:event_allClearPadActionPerformed

    private void multiplyPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("*"));
    }//GEN-LAST:event_multiplyPadActionPerformed

    private void dividePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividePadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("/"));
    }//GEN-LAST:event_dividePadActionPerformed

    private void plusPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("+"));
    }//GEN-LAST:event_plusPadActionPerformed

    private void minusPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("-"));
    }//GEN-LAST:event_minusPadActionPerformed

    private void leftBracesPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBracesPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("("));
    }//GEN-LAST:event_leftBracesPadActionPerformed

    private void rightBracesPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBracesPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat(")"));
    }//GEN-LAST:event_rightBracesPadActionPerformed

    private void sinPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("sin"));
    }//GEN-LAST:event_sinPadActionPerformed

    private void cosPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("cos"));
    }//GEN-LAST:event_cosPadActionPerformed

    private void tanPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("tan"));
    }//GEN-LAST:event_tanPadActionPerformed

    private void factPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("!"));
    }//GEN-LAST:event_factPadActionPerformed

    private void permutationPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permutationPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("P("));
    }//GEN-LAST:event_permutationPadActionPerformed

    private void combinationPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combinationPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("C("));
    }//GEN-LAST:event_combinationPadActionPerformed

    private void eulerPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulerPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("exp("));
    }//GEN-LAST:event_eulerPadActionPerformed

    private void logPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("log("));
    }//GEN-LAST:event_logPadActionPerformed

    private void cbrtPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrtPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("root(3, "));
    }//GEN-LAST:event_cbrtPadActionPerformed

    private void modPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("mod("));
    }//GEN-LAST:event_modPadActionPerformed

    private void expPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("^"));
    }//GEN-LAST:event_expPadActionPerformed

    private void sqrtPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat("sqrt("));
    }//GEN-LAST:event_sqrtPadActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allClearPad;
    private javax.swing.JButton cbrtPad;
    private javax.swing.JButton combinationPad;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JButton cosPad;
    private javax.swing.JButton decimalPad;
    private javax.swing.JButton deletePad;
    private javax.swing.JButton dividePad;
    private javax.swing.JButton eightPad;
    private javax.swing.JButton equalPad;
    private javax.swing.JButton eulerPad;
    private javax.swing.JButton expPad;
    private javax.swing.JButton factPad;
    private javax.swing.JButton fivePad;
    private javax.swing.JButton fourPad;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton leftBracesPad;
    private javax.swing.JButton logPad;
    private javax.swing.JButton minusPad;
    private javax.swing.JButton modPad;
    private javax.swing.JButton multiplyPad;
    private javax.swing.JButton ninePad;
    private javax.swing.JButton onePad;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton permutationPad;
    private javax.swing.JButton plusPad;
    private javax.swing.JButton rightBracesPad;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton sevenPad;
    private javax.swing.JButton sinPad;
    private javax.swing.JButton sixPad;
    private javax.swing.JButton sqrtPad;
    private javax.swing.JButton tanPad;
    private javax.swing.JButton threePad;
    private javax.swing.JButton twoPad;
    private javax.swing.JButton zeroPad;
    // End of variables declaration//GEN-END:variables
}
