/**
 * Nama             : Raissa Christabel Sebayang - 140810240008
 *                    Abraham Gomes Samosir - 140810240044
 *                    Haris Herdiansyah - 140810240074
 * Program Utama    : Aplikasi Kalkulator Scientific
 * Modul            : CalculatorFrame.java
 * Deskripsi        : Kelas tampilan utama dari aplikasi kalkulator scientific.
 * Tanggal          : 11 November 2025
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.view;

import calculator.service.CalculatorService;

import javax.swing.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author haris
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculatorFrame.class.getName());
    private final CalculatorService calculatorService;

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        this.calculatorService = new CalculatorService();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        outputField = new javax.swing.JTextField();
        decimalPad = new javax.swing.JButton();
        zeroPad = new javax.swing.JButton();
        equalPad = new javax.swing.JButton();
        onePad = new javax.swing.JButton();
        twoPad = new javax.swing.JButton();
        threePad = new javax.swing.JButton();
        fourPad = new javax.swing.JButton();
        fivePad = new javax.swing.JButton();
        sixPad = new javax.swing.JButton();
        sevenPad = new javax.swing.JButton();
        eightPad = new javax.swing.JButton();
        ninePad = new javax.swing.JButton();
        deletePad = new javax.swing.JButton();
        allClearPad = new javax.swing.JButton();
        multiplyPad = new javax.swing.JButton();
        dividePad = new javax.swing.JButton();
        plusPad = new javax.swing.JButton();
        minusPad = new javax.swing.JButton();
        leftBracesPad = new javax.swing.JButton();
        rightBracesPad = new javax.swing.JButton();
        sinPad = new javax.swing.JButton();
        cosPad = new javax.swing.JButton();
        tanPad = new javax.swing.JButton();
        factPad = new javax.swing.JButton();
        permutationPad = new javax.swing.JButton();
        combinationPad = new javax.swing.JButton();
        eulerPad = new javax.swing.JButton();
        lnPad = new javax.swing.JButton();
        log10Pad = new javax.swing.JButton();
        logPad = new javax.swing.JButton();
        cbrtPad = new javax.swing.JButton();
        modPad = new javax.swing.JButton();
        expPad = new javax.swing.JButton();
        sqrtPad = new javax.swing.JButton();
        copyrightLabel = new javax.swing.JLabel();
        piPad = new javax.swing.JButton();
        commaPad = new javax.swing.JButton();
        radianPad = new javax.swing.JButton();
        degreePad = new javax.swing.JButton();
        modeLabel = new javax.swing.JLabel();
        modeValue = new javax.swing.JLabel();
        toLeftPad = new javax.swing.JButton();
        toRightPad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rootPanel.setBackground(new java.awt.Color(250, 250, 250));

        inputField.setEditable(false);
        inputField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputFieldKeyPressed(evt);
            }
        });

        outputField.setEditable(false);
        outputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outputField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        decimalPad.setBackground(new java.awt.Color(204, 204, 204));
        decimalPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        decimalPad.setText(".");
        decimalPad.setPreferredSize(new java.awt.Dimension(50, 50));
        decimalPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalPadActionPerformed(evt);
            }
        });

        zeroPad.setBackground(new java.awt.Color(204, 204, 204));
        zeroPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        zeroPad.setText("0");
        zeroPad.setPreferredSize(new java.awt.Dimension(50, 50));
        zeroPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroPadActionPerformed(evt);
            }
        });

        equalPad.setBackground(new java.awt.Color(102, 102, 102));
        equalPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        equalPad.setForeground(new java.awt.Color(255, 255, 255));
        equalPad.setText("=");
        equalPad.setPreferredSize(new java.awt.Dimension(50, 50));
        equalPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalPadActionPerformed(evt);
            }
        });

        onePad.setBackground(new java.awt.Color(204, 204, 204));
        onePad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        onePad.setText("1");
        onePad.setPreferredSize(new java.awt.Dimension(50, 50));
        onePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onePadActionPerformed(evt);
            }
        });

        twoPad.setBackground(new java.awt.Color(204, 204, 204));
        twoPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        twoPad.setText("2");
        twoPad.setPreferredSize(new java.awt.Dimension(50, 50));
        twoPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoPadActionPerformed(evt);
            }
        });

        threePad.setBackground(new java.awt.Color(204, 204, 204));
        threePad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        threePad.setText("3");
        threePad.setPreferredSize(new java.awt.Dimension(50, 50));
        threePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threePadActionPerformed(evt);
            }
        });

        fourPad.setBackground(new java.awt.Color(204, 204, 204));
        fourPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fourPad.setText("4");
        fourPad.setPreferredSize(new java.awt.Dimension(50, 50));
        fourPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourPadActionPerformed(evt);
            }
        });

        fivePad.setBackground(new java.awt.Color(204, 204, 204));
        fivePad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fivePad.setText("5");
        fivePad.setPreferredSize(new java.awt.Dimension(50, 50));
        fivePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivePadActionPerformed(evt);
            }
        });

        sixPad.setBackground(new java.awt.Color(204, 204, 204));
        sixPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sixPad.setText("6");
        sixPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sixPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixPadActionPerformed(evt);
            }
        });

        sevenPad.setBackground(new java.awt.Color(204, 204, 204));
        sevenPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sevenPad.setText("7");
        sevenPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sevenPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenPadActionPerformed(evt);
            }
        });

        eightPad.setBackground(new java.awt.Color(204, 204, 204));
        eightPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eightPad.setText("8");
        eightPad.setPreferredSize(new java.awt.Dimension(50, 50));
        eightPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightPadActionPerformed(evt);
            }
        });

        ninePad.setBackground(new java.awt.Color(204, 204, 204));
        ninePad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ninePad.setText("9");
        ninePad.setPreferredSize(new java.awt.Dimension(50, 50));
        ninePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninePadActionPerformed(evt);
            }
        });

        deletePad.setBackground(new java.awt.Color(255, 0, 0));
        deletePad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deletePad.setForeground(new java.awt.Color(255, 255, 255));
        deletePad.setText("D");
        deletePad.setPreferredSize(new java.awt.Dimension(50, 50));
        deletePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePadActionPerformed(evt);
            }
        });

        allClearPad.setBackground(new java.awt.Color(255, 0, 0));
        allClearPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        allClearPad.setForeground(new java.awt.Color(255, 255, 255));
        allClearPad.setText("AC");
        allClearPad.setPreferredSize(new java.awt.Dimension(50, 50));
        allClearPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allClearPadActionPerformed(evt);
            }
        });

        multiplyPad.setBackground(new java.awt.Color(204, 204, 204));
        multiplyPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        multiplyPad.setText("*");
        multiplyPad.setPreferredSize(new java.awt.Dimension(50, 50));
        multiplyPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyPadActionPerformed(evt);
            }
        });

        dividePad.setBackground(new java.awt.Color(204, 204, 204));
        dividePad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dividePad.setText("/");
        dividePad.setPreferredSize(new java.awt.Dimension(50, 50));
        dividePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividePadActionPerformed(evt);
            }
        });

        plusPad.setBackground(new java.awt.Color(204, 204, 204));
        plusPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        plusPad.setText("+");
        plusPad.setPreferredSize(new java.awt.Dimension(50, 50));
        plusPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusPadActionPerformed(evt);
            }
        });

        minusPad.setBackground(new java.awt.Color(204, 204, 204));
        minusPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        minusPad.setText("-");
        minusPad.setPreferredSize(new java.awt.Dimension(50, 50));
        minusPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusPadActionPerformed(evt);
            }
        });

        leftBracesPad.setBackground(new java.awt.Color(204, 204, 204));
        leftBracesPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        leftBracesPad.setText("(");
        leftBracesPad.setPreferredSize(new java.awt.Dimension(50, 50));
        leftBracesPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBracesPadActionPerformed(evt);
            }
        });

        rightBracesPad.setBackground(new java.awt.Color(204, 204, 204));
        rightBracesPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rightBracesPad.setText(")");
        rightBracesPad.setPreferredSize(new java.awt.Dimension(50, 50));
        rightBracesPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBracesPadActionPerformed(evt);
            }
        });

        sinPad.setBackground(new java.awt.Color(102, 102, 102));
        sinPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sinPad.setForeground(new java.awt.Color(255, 255, 255));
        sinPad.setText("sin");
        sinPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sinPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinPadActionPerformed(evt);
            }
        });

        cosPad.setBackground(new java.awt.Color(102, 102, 102));
        cosPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cosPad.setForeground(new java.awt.Color(255, 255, 255));
        cosPad.setText("cos");
        cosPad.setPreferredSize(new java.awt.Dimension(50, 50));
        cosPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosPadActionPerformed(evt);
            }
        });

        tanPad.setBackground(new java.awt.Color(102, 102, 102));
        tanPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tanPad.setForeground(new java.awt.Color(255, 255, 255));
        tanPad.setText("tan");
        tanPad.setPreferredSize(new java.awt.Dimension(50, 50));
        tanPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanPadActionPerformed(evt);
            }
        });

        factPad.setBackground(new java.awt.Color(255, 204, 51));
        factPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        factPad.setText("n!");
        factPad.setPreferredSize(new java.awt.Dimension(50, 50));
        factPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factPadActionPerformed(evt);
            }
        });

        permutationPad.setBackground(new java.awt.Color(255, 204, 51));
        permutationPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        permutationPad.setText("P()");
        permutationPad.setPreferredSize(new java.awt.Dimension(50, 50));
        permutationPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permutationPadActionPerformed(evt);
            }
        });

        combinationPad.setBackground(new java.awt.Color(255, 204, 51));
        combinationPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        combinationPad.setText("C()");
        combinationPad.setPreferredSize(new java.awt.Dimension(50, 50));
        combinationPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combinationPadActionPerformed(evt);
            }
        });

        eulerPad.setBackground(new java.awt.Color(255, 204, 51));
        eulerPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eulerPad.setText("exp");
        eulerPad.setPreferredSize(new java.awt.Dimension(50, 50));
        eulerPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulerPadActionPerformed(evt);
            }
        });

        lnPad.setBackground(new java.awt.Color(255, 204, 51));
        lnPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lnPad.setText("ln");
        lnPad.setPreferredSize(new java.awt.Dimension(50, 50));
        lnPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnPadActionPerformed(evt);
            }
        });

        log10Pad.setBackground(new java.awt.Color(255, 204, 51));
        log10Pad.setText("L10");
        log10Pad.setPreferredSize(new java.awt.Dimension(50, 50));
        log10Pad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log10PadActionPerformed(evt);
            }
        });

        logPad.setBackground(new java.awt.Color(255, 204, 51));
        logPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logPad.setText("log");
        logPad.setPreferredSize(new java.awt.Dimension(50, 50));
        logPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logPadActionPerformed(evt);
            }
        });

        cbrtPad.setBackground(new java.awt.Color(255, 204, 51));
        cbrtPad.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        cbrtPad.setText("cbrt");
        cbrtPad.setPreferredSize(new java.awt.Dimension(50, 50));
        cbrtPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrtPadActionPerformed(evt);
            }
        });

        modPad.setBackground(new java.awt.Color(204, 204, 204));
        modPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modPad.setText("%");
        modPad.setPreferredSize(new java.awt.Dimension(50, 50));
        modPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPadActionPerformed(evt);
            }
        });

        expPad.setBackground(new java.awt.Color(204, 204, 204));
        expPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        expPad.setText("^");
        expPad.setPreferredSize(new java.awt.Dimension(50, 50));
        expPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expPadActionPerformed(evt);
            }
        });

        sqrtPad.setBackground(new java.awt.Color(255, 204, 51));
        sqrtPad.setText("sqrt");
        sqrtPad.setPreferredSize(new java.awt.Dimension(50, 50));
        sqrtPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtPadActionPerformed(evt);
            }
        });

        copyrightLabel.setText("Copyright @ Raissa (08) - Abraham (44) - Haris (74)");

        piPad.setBackground(new java.awt.Color(204, 204, 204));
        piPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        piPad.setText("PI");
        piPad.setPreferredSize(new java.awt.Dimension(50, 50));
        piPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piPadActionPerformed(evt);
            }
        });

        commaPad.setBackground(new java.awt.Color(204, 204, 204));
        commaPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        commaPad.setText(",");
        commaPad.setPreferredSize(new java.awt.Dimension(50, 50));
        commaPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commaPadActionPerformed(evt);
            }
        });

        radianPad.setBackground(new java.awt.Color(51, 51, 255));
        radianPad.setForeground(new java.awt.Color(255, 255, 255));
        radianPad.setText("rad");
        radianPad.setPreferredSize(new java.awt.Dimension(50, 50));
        radianPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radianPadActionPerformed(evt);
            }
        });

        degreePad.setBackground(new java.awt.Color(51, 51, 255));
        degreePad.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        degreePad.setForeground(new java.awt.Color(255, 255, 255));
        degreePad.setText("deg");
        degreePad.setPreferredSize(new java.awt.Dimension(50, 50));
        degreePad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreePadActionPerformed(evt);
            }
        });

        modeLabel.setText("Mode");

        modeValue.setText(this.calculatorService.isDegree() ? "Degree" : "Radian");

        toLeftPad.setBackground(new java.awt.Color(204, 204, 204));
        toLeftPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toLeftPad.setText("<");
        toLeftPad.setPreferredSize(new java.awt.Dimension(50, 50));
        toLeftPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toLeftPadActionPerformed(evt);
            }
        });

        toRightPad.setBackground(new java.awt.Color(204, 204, 204));
        toRightPad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        toRightPad.setText(">");
        toRightPad.setPreferredSize(new java.awt.Dimension(50, 50));
        toRightPad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toRightPadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(rootPanelLayout.createSequentialGroup()
                            .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fourPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sevenPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                            .addComponent(eightPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ninePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                            .addComponent(fivePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(sixPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(onePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(twoPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(threePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(decimalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(zeroPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(piPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                                    .addComponent(commaPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(radianPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(degreePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(33, 33, 33)
                            .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(toLeftPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(toRightPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(multiplyPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dividePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(plusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(minusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(leftBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rightBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(modPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(expPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)
                            .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(lnPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(log10Pad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(logPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(factPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(permutationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(combinationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addComponent(sinPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cosPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tanPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(rootPanelLayout.createSequentialGroup()
                                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                            .addComponent(eulerPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(sqrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(rootPanelLayout.createSequentialGroup()
                                            .addComponent(deletePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(allClearPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(equalPad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addComponent(outputField)
                        .addComponent(inputField)
                        .addComponent(copyrightLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(modeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(modeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeLabel)
                    .addComponent(modeValue))
                .addGap(4, 4, 4)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sinPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cosPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commaPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radianPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(degreePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(multiplyPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dividePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(factPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(permutationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combinationPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(log10Pad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rightBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leftBracesPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sqrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eulerPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbrtPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allClearPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLeftPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toRightPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ninePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fivePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threePad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(decimalPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(piPad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(copyrightLabel)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continueOperationHandling() {
        if (!outputField.getText().isEmpty()) {
            inputField.setText(outputField.getText());
            outputField.setText("");
        }
    }

    private void decimalPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("."));
        inputField.requestFocus();
    }//GEN-LAST:event_decimalPadActionPerformed

    private void zeroPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("0"));
        inputField.requestFocus();
    }//GEN-LAST:event_zeroPadActionPerformed

    private void equalPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalPadActionPerformed
        // TODO add your handling code here:
        double result = calculatorService.calculateExpression(inputField.getText());

        if (Double.isNaN(result)) {
            JOptionPane.showMessageDialog(this, "Invalid Expression", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            outputField.setText(Double.toString(result));
        }

    }//GEN-LAST:event_equalPadActionPerformed

    private void onePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onePadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("1"));
        inputField.requestFocus();
    }//GEN-LAST:event_onePadActionPerformed

    private void twoPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("2"));
        inputField.requestFocus();
    }//GEN-LAST:event_twoPadActionPerformed

    private void threePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threePadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("3"));
        inputField.requestFocus();
    }//GEN-LAST:event_threePadActionPerformed

    private void fourPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("4"));
        inputField.requestFocus();
    }//GEN-LAST:event_fourPadActionPerformed

    private void fivePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivePadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("5"));
        inputField.requestFocus();
    }//GEN-LAST:event_fivePadActionPerformed

    private void sixPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("6"));
        inputField.requestFocus();
    }//GEN-LAST:event_sixPadActionPerformed

    private void sevenPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("7"));
        inputField.requestFocus();
    }//GEN-LAST:event_sevenPadActionPerformed

    private void eightPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("8"));
        inputField.requestFocus();
    }//GEN-LAST:event_eightPadActionPerformed

    private void ninePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninePadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("9"));
        inputField.requestFocus();
    }//GEN-LAST:event_ninePadActionPerformed

    private void deletePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePadActionPerformed
        // TODO add your handling code here:
        String currentText = inputField.getText();
        int caretPos = inputField.getCaretPosition();

        if (!currentText.isEmpty() && caretPos > 0) {
            // Delete one character before the caret
            String newText = currentText.substring(0, caretPos - 1)
                    + currentText.substring(caretPos);
            inputField.setText(newText);
            inputField.setCaretPosition(caretPos - 1); // keep caret consistent
        }

        // Optional: if you really want to clear both when outputField isn't empty
        if (!currentText.isEmpty() && !outputField.getText().isEmpty()) {
            inputField.setText("");
            outputField.setText("");
        }
    }//GEN-LAST:event_deletePadActionPerformed

    private void allClearPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allClearPadActionPerformed
        // TODO add your handling code here:
        inputField.setText("");
        outputField.setText("");
    }//GEN-LAST:event_allClearPadActionPerformed

    private void multiplyPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("*"));
        inputField.requestFocus();
    }//GEN-LAST:event_multiplyPadActionPerformed

    private void dividePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividePadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("/"));
        inputField.requestFocus();
    }//GEN-LAST:event_dividePadActionPerformed

    private void plusPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("+"));
        inputField.requestFocus();
    }//GEN-LAST:event_plusPadActionPerformed

    private void minusPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("-"));
        inputField.requestFocus();
    }//GEN-LAST:event_minusPadActionPerformed

    private void leftBracesPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBracesPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("("));
        inputField.requestFocus();
    }//GEN-LAST:event_leftBracesPadActionPerformed

    private void rightBracesPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBracesPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat(")"));
        inputField.requestFocus();
    }//GEN-LAST:event_rightBracesPadActionPerformed

    private void sinPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("sin"));
        inputField.requestFocus();
    }//GEN-LAST:event_sinPadActionPerformed

    private void cosPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("cos"));
        inputField.requestFocus();
    }//GEN-LAST:event_cosPadActionPerformed

    private void tanPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("tan"));
        inputField.requestFocus();
    }//GEN-LAST:event_tanPadActionPerformed

    private void factPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("!"));
        inputField.requestFocus();
    }//GEN-LAST:event_factPadActionPerformed

    private void permutationPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permutationPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("P("));
        inputField.requestFocus();
    }//GEN-LAST:event_permutationPadActionPerformed

    private void combinationPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combinationPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("C("));
        inputField.requestFocus();
    }//GEN-LAST:event_combinationPadActionPerformed

    private void eulerPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulerPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("exp("));
        inputField.requestFocus();
    }//GEN-LAST:event_eulerPadActionPerformed

    private void lnPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("ln("));
        inputField.requestFocus();
    }//GEN-LAST:event_lnPadActionPerformed

    private void cbrtPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrtPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("root(3, "));
        inputField.requestFocus();
    }//GEN-LAST:event_cbrtPadActionPerformed

    private void modPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("mod("));
        inputField.requestFocus();
    }//GEN-LAST:event_modPadActionPerformed

    private void expPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("^"));
        inputField.requestFocus();
    }//GEN-LAST:event_expPadActionPerformed

    private void sqrtPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("sqrt("));
        inputField.requestFocus();
    }//GEN-LAST:event_sqrtPadActionPerformed

    private void piPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("pi"));
        inputField.requestFocus();
    }//GEN-LAST:event_piPadActionPerformed

    private void log10PadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log10PadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("log10("));
        inputField.requestFocus();
    }//GEN-LAST:event_log10PadActionPerformed

    private void logPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logPadActionPerformed
        // TODO add your handling code here:
        continueOperationHandling();
        inputField.setText(inputField.getText().concat("log("));
        inputField.requestFocus();
    }//GEN-LAST:event_logPadActionPerformed

    private void commaPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commaPadActionPerformed
        // TODO add your handling code here:
        inputField.setText(inputField.getText().concat(","));
        inputField.requestFocus();
    }//GEN-LAST:event_commaPadActionPerformed

    private void radianPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radianPadActionPerformed
        // TODO add your handling code here:
        calculatorService.setRadiansMode();
        modeValue.setText(calculatorService.isDegree() ? "Degree" : "Radian");
    }//GEN-LAST:event_radianPadActionPerformed

    private void degreePadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreePadActionPerformed
        // TODO add your handling code here:
        calculatorService.setDegreesMode();
        modeValue.setText(calculatorService.isDegree() ? "Degree" : "Radian");
    }//GEN-LAST:event_degreePadActionPerformed

    private void toLeftPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toLeftPadActionPerformed
        // TODO add your handling code here:
        int pos = inputField.getCaretPosition();
        if (pos > 0) {
            inputField.requestFocus();
            inputField.setCaretPosition(pos - 1);
            inputField.requestFocus();
        }
    }//GEN-LAST:event_toLeftPadActionPerformed

    private void toRightPadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toRightPadActionPerformed
        // TODO add your handling code here:
        int pos = inputField.getCaretPosition();
        if (pos < inputField.getText().length()) {
            inputField.requestFocus();
            inputField.setCaretPosition(pos + 1);
            inputField.requestFocus();
        }
    }//GEN-LAST:event_toRightPadActionPerformed

    private void inputFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double result = calculatorService.calculateExpression(inputField.getText());

            if (Double.isNaN(result)) {
                JOptionPane.showMessageDialog(this, "Invalid Expression", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                outputField.setText(Double.toString(result));
            }
        }
    }//GEN-LAST:event_inputFieldKeyPressed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allClearPad;
    private javax.swing.JButton cbrtPad;
    private javax.swing.JButton combinationPad;
    private javax.swing.JButton commaPad;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JButton cosPad;
    private javax.swing.JButton decimalPad;
    private javax.swing.JButton degreePad;
    private javax.swing.JButton deletePad;
    private javax.swing.JButton dividePad;
    private javax.swing.JButton eightPad;
    private javax.swing.JButton equalPad;
    private javax.swing.JButton eulerPad;
    private javax.swing.JButton expPad;
    private javax.swing.JButton factPad;
    private javax.swing.JButton fivePad;
    private javax.swing.JButton fourPad;
    private javax.swing.JTextField inputField;
    private javax.swing.JButton leftBracesPad;
    private javax.swing.JButton lnPad;
    private javax.swing.JButton log10Pad;
    private javax.swing.JButton logPad;
    private javax.swing.JButton minusPad;
    private javax.swing.JButton modPad;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JLabel modeValue;
    private javax.swing.JButton multiplyPad;
    private javax.swing.JButton ninePad;
    private javax.swing.JButton onePad;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton permutationPad;
    private javax.swing.JButton piPad;
    private javax.swing.JButton plusPad;
    private javax.swing.JButton radianPad;
    private javax.swing.JButton rightBracesPad;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton sevenPad;
    private javax.swing.JButton sinPad;
    private javax.swing.JButton sixPad;
    private javax.swing.JButton sqrtPad;
    private javax.swing.JButton tanPad;
    private javax.swing.JButton threePad;
    private javax.swing.JButton toLeftPad;
    private javax.swing.JButton toRightPad;
    private javax.swing.JButton twoPad;
    private javax.swing.JButton zeroPad;
    // End of variables declaration//GEN-END:variables
}
