/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator.view;

/**
 *
 * @author haris
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculatorFrame.class.getName());

    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        numpadPanel = new javax.swing.JPanel();
        numpadDot = new javax.swing.JButton();
        numpad0 = new javax.swing.JButton();
        numpadEqual = new javax.swing.JButton();
        numpad1 = new javax.swing.JButton();
        numpad2 = new javax.swing.JButton();
        numpad3 = new javax.swing.JButton();
        numpad4 = new javax.swing.JButton();
        numpad5 = new javax.swing.JButton();
        numpad6 = new javax.swing.JButton();
        numpad7 = new javax.swing.JButton();
        numpad8 = new javax.swing.JButton();
        numpad9 = new javax.swing.JButton();
        operatorPanel = new javax.swing.JPanel();
        numpadPlus = new javax.swing.JButton();
        numpadMinus = new javax.swing.JButton();
        numpadMultiply = new javax.swing.JButton();
        numpadDivide = new javax.swing.JButton();
        numpadPower = new javax.swing.JButton();
        numpadRoot2 = new javax.swing.JButton();
        numpadRoot3 = new javax.swing.JButton();
        numpadFact = new javax.swing.JButton();
        numpadExp = new javax.swing.JButton();
        numpadLog = new javax.swing.JButton();
        numpadPerm = new javax.swing.JButton();
        numpadComb = new javax.swing.JButton();
        numpadSin = new javax.swing.JButton();
        numpadCos = new javax.swing.JButton();
        numpadTan = new javax.swing.JButton();
        numpadPI = new javax.swing.JButton();
        numpadClearAll = new javax.swing.JButton();
        numpadBackspace = new javax.swing.JButton();
        numpadBL = new javax.swing.JButton();
        numpadBR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputField.setEnabled(false);

        numpadDot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpadDot.setText(".");
        numpadDot.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadDot.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadDot.setName(""); // NOI18N
        numpadDot.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadDotActionPerformed(evt);
            }
        });

        numpad0.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad0.setText("0");
        numpad0.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad0.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad0.setName(""); // NOI18N
        numpad0.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad0ActionPerformed(evt);
            }
        });

        numpadEqual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpadEqual.setText("=");
        numpadEqual.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadEqual.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadEqual.setName(""); // NOI18N
        numpadEqual.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadEqualActionPerformed(evt);
            }
        });

        numpad1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad1.setText("1");
        numpad1.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad1.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad1.setName(""); // NOI18N
        numpad1.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad1ActionPerformed(evt);
            }
        });

        numpad2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad2.setText("2");
        numpad2.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad2.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad2.setName(""); // NOI18N
        numpad2.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad2ActionPerformed(evt);
            }
        });

        numpad3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad3.setText("3");
        numpad3.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad3.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad3.setName(""); // NOI18N
        numpad3.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad3ActionPerformed(evt);
            }
        });

        numpad4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad4.setText("4");
        numpad4.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad4.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad4.setName(""); // NOI18N
        numpad4.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad4ActionPerformed(evt);
            }
        });

        numpad5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad5.setText("5");
        numpad5.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad5.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad5.setName(""); // NOI18N
        numpad5.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad5ActionPerformed(evt);
            }
        });

        numpad6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad6.setText("6");
        numpad6.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad6.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad6.setName(""); // NOI18N
        numpad6.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad6ActionPerformed(evt);
            }
        });

        numpad7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad7.setText("7");
        numpad7.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad7.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad7.setName(""); // NOI18N
        numpad7.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad7ActionPerformed(evt);
            }
        });

        numpad8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad8.setText("8");
        numpad8.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad8.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad8.setName(""); // NOI18N
        numpad8.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad8ActionPerformed(evt);
            }
        });

        numpad9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpad9.setText("9");
        numpad9.setMaximumSize(new java.awt.Dimension(75, 75));
        numpad9.setMinimumSize(new java.awt.Dimension(75, 75));
        numpad9.setName(""); // NOI18N
        numpad9.setPreferredSize(new java.awt.Dimension(50, 50));
        numpad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpad9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout numpadPanelLayout = new javax.swing.GroupLayout(numpadPanel);
        numpadPanel.setLayout(numpadPanelLayout);
        numpadPanelLayout.setHorizontalGroup(
            numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
            .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(numpadPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(numpadPanelLayout.createSequentialGroup()
                            .addComponent(numpad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(numpad8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(numpad9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(numpadPanelLayout.createSequentialGroup()
                            .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(numpadDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numpad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numpad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(numpadPanelLayout.createSequentialGroup()
                                    .addComponent(numpad0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numpadEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(numpadPanelLayout.createSequentialGroup()
                                    .addComponent(numpad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numpad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(numpadPanelLayout.createSequentialGroup()
                                    .addComponent(numpad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(numpad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        numpadPanelLayout.setVerticalGroup(
            numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(numpadPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numpad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numpad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numpad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(numpadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numpadDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpad0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpadEqual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        numpadPlus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpadPlus.setText("+");
        numpadPlus.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadPlus.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadPlus.setName(""); // NOI18N
        numpadPlus.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadPlusActionPerformed(evt);
            }
        });

        numpadMinus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpadMinus.setText("-");
        numpadMinus.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadMinus.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadMinus.setName(""); // NOI18N
        numpadMinus.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadMinusActionPerformed(evt);
            }
        });

        numpadMultiply.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpadMultiply.setText("*");
        numpadMultiply.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadMultiply.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadMultiply.setName(""); // NOI18N
        numpadMultiply.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadMultiplyActionPerformed(evt);
            }
        });

        numpadDivide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadDivide.setText("/");
        numpadDivide.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadDivide.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadDivide.setName(""); // NOI18N
        numpadDivide.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadDivideActionPerformed(evt);
            }
        });

        numpadPower.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        numpadPower.setText("^");
        numpadPower.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadPower.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadPower.setName(""); // NOI18N
        numpadPower.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadPowerActionPerformed(evt);
            }
        });

        numpadRoot2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadRoot2.setText("√2");
        numpadRoot2.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadRoot2.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadRoot2.setName(""); // NOI18N
        numpadRoot2.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadRoot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadRoot2ActionPerformed(evt);
            }
        });

        numpadRoot3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadRoot3.setText("√3");
        numpadRoot3.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadRoot3.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadRoot3.setName(""); // NOI18N
        numpadRoot3.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadRoot3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadRoot3ActionPerformed(evt);
            }
        });

        numpadFact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadFact.setText("n!");
        numpadFact.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadFact.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadFact.setName(""); // NOI18N
        numpadFact.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadFactActionPerformed(evt);
            }
        });

        numpadExp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadExp.setText("exp");
        numpadExp.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadExp.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadExp.setName(""); // NOI18N
        numpadExp.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadExpActionPerformed(evt);
            }
        });

        numpadLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadLog.setText("log");
        numpadLog.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadLog.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadLog.setName(""); // NOI18N
        numpadLog.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadLogActionPerformed(evt);
            }
        });

        numpadPerm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadPerm.setText("P()");
        numpadPerm.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadPerm.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadPerm.setName(""); // NOI18N
        numpadPerm.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadPerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadPermActionPerformed(evt);
            }
        });

        numpadComb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadComb.setText("C()");
        numpadComb.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadComb.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadComb.setName(""); // NOI18N
        numpadComb.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadCombActionPerformed(evt);
            }
        });

        numpadSin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadSin.setText("sin");
        numpadSin.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadSin.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadSin.setName(""); // NOI18N
        numpadSin.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadSinActionPerformed(evt);
            }
        });

        numpadCos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadCos.setText("cos");
        numpadCos.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadCos.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadCos.setName(""); // NOI18N
        numpadCos.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadCosActionPerformed(evt);
            }
        });

        numpadTan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadTan.setText("tan");
        numpadTan.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadTan.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadTan.setName(""); // NOI18N
        numpadTan.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadTanActionPerformed(evt);
            }
        });

        numpadPI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadPI.setText("PI");
        numpadPI.setMaximumSize(new java.awt.Dimension(75, 75));
        numpadPI.setMinimumSize(new java.awt.Dimension(75, 75));
        numpadPI.setName(""); // NOI18N
        numpadPI.setPreferredSize(new java.awt.Dimension(50, 50));
        numpadPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operatorPanelLayout = new javax.swing.GroupLayout(operatorPanel);
        operatorPanel.setLayout(operatorPanelLayout);
        operatorPanelLayout.setHorizontalGroup(
            operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operatorPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operatorPanelLayout.createSequentialGroup()
                        .addComponent(numpadSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numpadCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numpadTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numpadPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(operatorPanelLayout.createSequentialGroup()
                            .addComponent(numpadExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadPerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numpadComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(operatorPanelLayout.createSequentialGroup()
                            .addComponent(numpadPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadRoot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadRoot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(operatorPanelLayout.createSequentialGroup()
                            .addComponent(numpadPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(numpadDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        operatorPanelLayout.setVerticalGroup(
            operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpadPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadTan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadCos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadSin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numpadComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpadPerm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpadLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numpadExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpadFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadRoot3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadRoot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(operatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpadPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        numpadClearAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadClearAll.setText("Clear All");
        numpadClearAll.setMaximumSize(new java.awt.Dimension(75, 100));
        numpadClearAll.setMinimumSize(new java.awt.Dimension(75, 100));
        numpadClearAll.setPreferredSize(new java.awt.Dimension(75, 100));
        numpadClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadClearAllActionPerformed(evt);
            }
        });

        numpadBackspace.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadBackspace.setText("Backspace");
        numpadBackspace.setMaximumSize(new java.awt.Dimension(75, 100));
        numpadBackspace.setMinimumSize(new java.awt.Dimension(75, 100));
        numpadBackspace.setPreferredSize(new java.awt.Dimension(75, 100));
        numpadBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadBackspaceActionPerformed(evt);
            }
        });

        numpadBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadBL.setText("(");
        numpadBL.setMaximumSize(new java.awt.Dimension(75, 100));
        numpadBL.setMinimumSize(new java.awt.Dimension(75, 100));
        numpadBL.setPreferredSize(new java.awt.Dimension(75, 100));
        numpadBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadBLActionPerformed(evt);
            }
        });

        numpadBR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numpadBR.setText(")");
        numpadBR.setMaximumSize(new java.awt.Dimension(75, 100));
        numpadBR.setMinimumSize(new java.awt.Dimension(75, 100));
        numpadBR.setPreferredSize(new java.awt.Dimension(75, 100));
        numpadBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpadBRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                        .addComponent(operatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numpadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(numpadClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numpadBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(numpadBL, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numpadBR, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(inputField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numpadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(operatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numpadClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numpadBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numpadBL, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numpadBR, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numpad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad5ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("5"));
        }
    }//GEN-LAST:event_numpad5ActionPerformed

    private void numpad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad8ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("8"));
        }
    }//GEN-LAST:event_numpad8ActionPerformed

    private void numpadEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadEqualActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("="));
        }
    }//GEN-LAST:event_numpadEqualActionPerformed

    private void numpadCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadCombActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("C"));
        }
    }//GEN-LAST:event_numpadCombActionPerformed

    private void numpadPermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadPermActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("P"));
        }
    }//GEN-LAST:event_numpadPermActionPerformed

    private void numpadLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadLogActionPerformed
        // TODO add your handling code here
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("L"));
        }
    }//GEN-LAST:event_numpadLogActionPerformed

    private void numpadPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadPowerActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("^"));
        }
    }//GEN-LAST:event_numpadPowerActionPerformed

    private void numpadExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadExpActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("e"));
        }
    }//GEN-LAST:event_numpadExpActionPerformed

    private void numpadDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadDotActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("."));
        }
    }//GEN-LAST:event_numpadDotActionPerformed

    private void numpad0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad0ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("0"));
        }
    }//GEN-LAST:event_numpad0ActionPerformed

    private void numpad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad1ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("1"));
        }
    }//GEN-LAST:event_numpad1ActionPerformed

    private void numpad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad2ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("2"));
        }
    }//GEN-LAST:event_numpad2ActionPerformed

    private void numpad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad3ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("3"));
        }
    }//GEN-LAST:event_numpad3ActionPerformed

    private void numpad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad4ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("4"));
        }
    }//GEN-LAST:event_numpad4ActionPerformed

    private void numpad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad6ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("6"));
        }
    }//GEN-LAST:event_numpad6ActionPerformed

    private void numpad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad7ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("7"));
        }
    }//GEN-LAST:event_numpad7ActionPerformed

    private void numpad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpad9ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("9"));
        }
    }//GEN-LAST:event_numpad9ActionPerformed

    private void numpadPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadPlusActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("+"));
        }
    }//GEN-LAST:event_numpadPlusActionPerformed

    private void numpadMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadMinusActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("-"));
        }
    }//GEN-LAST:event_numpadMinusActionPerformed

    private void numpadMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadMultiplyActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("*"));
        }
    }//GEN-LAST:event_numpadMultiplyActionPerformed

    private void numpadDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadDivideActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("/"));
        }
    }//GEN-LAST:event_numpadDivideActionPerformed

    private void numpadBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadBLActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("("));
        }
    }//GEN-LAST:event_numpadBLActionPerformed

    private void numpadBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadBRActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat(")"));
        }
    }//GEN-LAST:event_numpadBRActionPerformed

    private void numpadClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadClearAllActionPerformed
        // TODO add your handling code here
        inputField.setText("");
    }//GEN-LAST:event_numpadClearAllActionPerformed

    private void numpadRoot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadRoot2ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("sq"));
        }
    }//GEN-LAST:event_numpadRoot2ActionPerformed

    private void numpadRoot3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadRoot3ActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("cb"));
        }
    }//GEN-LAST:event_numpadRoot3ActionPerformed

    private void numpadFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadFactActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("F"));
        }
    }//GEN-LAST:event_numpadFactActionPerformed

    private void numpadSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadSinActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("sin"));
        }
    }//GEN-LAST:event_numpadSinActionPerformed

    private void numpadCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadCosActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("cos"));
        }
    }//GEN-LAST:event_numpadCosActionPerformed

    private void numpadTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadTanActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("tan"));
        }
    }//GEN-LAST:event_numpadTanActionPerformed

    private void numpadPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadPIActionPerformed
        // TODO add your handling code here:
        if (inputField.getText().length() < 20) {
            inputField.setText(inputField.getText().concat("3.14"));
        }
    }//GEN-LAST:event_numpadPIActionPerformed

    private void numpadBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpadBackspaceActionPerformed
        // TODO add your handling code here:
        if (!inputField.getText().isEmpty()) {
            inputField.setText(inputField.getText().substring(0, inputField.getText().length() - 1));
        }
    }//GEN-LAST:event_numpadBackspaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputField;
    private javax.swing.JButton numpad0;
    private javax.swing.JButton numpad1;
    private javax.swing.JButton numpad2;
    private javax.swing.JButton numpad3;
    private javax.swing.JButton numpad4;
    private javax.swing.JButton numpad5;
    private javax.swing.JButton numpad6;
    private javax.swing.JButton numpad7;
    private javax.swing.JButton numpad8;
    private javax.swing.JButton numpad9;
    private javax.swing.JButton numpadBL;
    private javax.swing.JButton numpadBR;
    private javax.swing.JButton numpadBackspace;
    private javax.swing.JButton numpadClearAll;
    private javax.swing.JButton numpadComb;
    private javax.swing.JButton numpadCos;
    private javax.swing.JButton numpadDivide;
    private javax.swing.JButton numpadDot;
    private javax.swing.JButton numpadEqual;
    private javax.swing.JButton numpadExp;
    private javax.swing.JButton numpadFact;
    private javax.swing.JButton numpadLog;
    private javax.swing.JButton numpadMinus;
    private javax.swing.JButton numpadMultiply;
    private javax.swing.JButton numpadPI;
    private javax.swing.JPanel numpadPanel;
    private javax.swing.JButton numpadPerm;
    private javax.swing.JButton numpadPlus;
    private javax.swing.JButton numpadPower;
    private javax.swing.JButton numpadRoot2;
    private javax.swing.JButton numpadRoot3;
    private javax.swing.JButton numpadSin;
    private javax.swing.JButton numpadTan;
    private javax.swing.JPanel operatorPanel;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables
}
