/**
 * Nama             : Raissa Christabel Sebayang - 140810240008
 *                    Abraham Gomes Samosir - 140810240044
 *                    Haris Herdiansyah - 140810240074
 * Program Utama    : Aplikasi Parkir Pelabuhan
 * Modul            : ParkingService.java
 * Deskripsi        : Kelas untuk menangani logika bisnis aplikasi parkir pelabuhan.
 * Tanggal          : 11 November 2025
 */

package parking.view;

import parking.classes.*;
import parking.service.ParkingService;

import javax.swing.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author haris
 */
public class ParkingUIFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParkingUIFrame.class.getName());
    private VehicleType selectedType;

    /**
     * Creates new form ParkingUIFrame
     */
    public ParkingUIFrame() {
        initComponents();

        ParkingService service = ParkingService.getInstance();
        String areaOutputHeader = "No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tSelisih Waktu\t\tBiaya Parkir";
        areaOutput.setText("");
        areaOutput.setText(areaOutputHeader.concat(service.getMappedVehicleList()));
    }
    
    public ParkingUIFrame(VehicleType selectedType) {
        this.selectedType = selectedType;

        initComponents();

        ParkingService service = ParkingService.getInstance();
        String areaOutputHeader = "No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tSelisih Waktu\t\tBiaya Parkir";
        areaOutput.setText("");
        areaOutput.setText(areaOutputHeader.concat(service.getMappedVehicleList()));

        switch (selectedType) {
            case CAR -> addBtn.setText("Tambah Mobil");
            case MOTORCYCLE -> addBtn.setText("Tambah Motor");
            case TRUCK -> addBtn.setText("Tambah Truk");
        }

        licensePlateField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        licensePlateLabel = new javax.swing.JLabel();
        licensePlateField = new javax.swing.JTextField();
        entryTimeLabel = new javax.swing.JLabel();
        entryTimeField = new javax.swing.JTextField();
        exitTimeLabel = new javax.swing.JLabel();
        exitTimeField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextArea();
        addBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalValue = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rootPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Masukkan Kendaraan"));

        exitBtn.setText("Selesai");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Kembali");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        licensePlateLabel.setText("No. Plat");

        licensePlateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                licensePlateFieldKeyPressed(evt);
            }
        });

        entryTimeLabel.setText("Waktu Masuk");

        entryTimeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entryTimeFieldKeyPressed(evt);
            }
        });

        exitTimeLabel.setText("Waktu Keluar");

        exitTimeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exitTimeFieldKeyPressed(evt);
            }
        });

        areaOutput.setEditable(false);
        areaOutput.setBackground(new java.awt.Color(255, 255, 255));
        areaOutput.setColumns(20);
        areaOutput.setRows(5);
        areaOutput.setText("No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tLama Parkir\t\tBiaya Parkir");
        jScrollPane1.setViewportView(areaOutput);

        addBtn.setText("Tambah");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Total");

        totalValue.setText("Rp0,00");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(rootPanelLayout.createSequentialGroup()
                        .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rootPanelLayout.createSequentialGroup()
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(exitTimeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(entryTimeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(licensePlateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(exitTimeField, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(entryTimeField)
                                    .addComponent(licensePlateField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                                .addComponent(exitBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                                .addComponent(resetBtn)
                                .addGap(18, 18, 18)
                                .addComponent(backBtn)))
                        .addGap(46, 46, 46))))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlateLabel)
                    .addComponent(licensePlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entryTimeLabel)
                    .addComponent(entryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitTimeLabel)
                    .addComponent(exitTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalValue))
                .addGap(18, 18, 18)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(backBtn)
                    .addComponent(resetBtn))
                .addGap(26, 26, 26))
        );

        copyright.setText("Copyright @ Raissa (08) - Abraham (44) - Haris (74)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(copyright)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetFieldAction() {
        licensePlateField.setText("");
        entryTimeField.setText("");
        exitTimeField.setText("");
    }

    private void addVehicleAction() {
        ParkingService service = ParkingService.getInstance();

        String licensePlate = licensePlateField.getText();
        DatesTime entryTime = service.datesTimeParser(entryTimeField.getText());
        DatesTime exitTime = service.datesTimeParser(exitTimeField.getText());

        try {
            Vehicle vehicle = switch (selectedType) {
                case CAR -> new Car(licensePlate, entryTime, exitTime);
                case MOTORCYCLE -> new Motorcycle(licensePlate, entryTime, exitTime);
                case TRUCK -> new Truck(licensePlate, entryTime, exitTime);
            };

            service.addVehicle(vehicle);

            String areaOutputHeader = "No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tSelisih Waktu\t\tBiaya Parkir";
            areaOutput.setText("");
            areaOutput.setText(areaOutputHeader.concat(service.getMappedVehicleList()));
            totalValue.setText("Rp" + String.format("%,.2f", service.calculateTotalRevenue()));

            resetFieldAction();
            licensePlateField.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        resetFieldAction();
        areaOutput.setText("No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tLama Parkir\t\tBiaya Parkir");
        totalValue.setText("Rp0,00");
        ParkingService service = ParkingService.getInstance();
        service.resetService();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        new MultiformFrame().setVisible(true); dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        addVehicleAction();
    }//GEN-LAST:event_addBtnActionPerformed

    private void licensePlateFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_licensePlateFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            entryTimeField.requestFocus();
        }
    }//GEN-LAST:event_licensePlateFieldKeyPressed

    private void entryTimeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entryTimeFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            exitTimeField.requestFocus();
        }
    }//GEN-LAST:event_entryTimeFieldKeyPressed

    private void exitTimeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exitTimeFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addVehicleAction();
        }
    }//GEN-LAST:event_exitTimeFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ParkingUIFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextArea areaOutput;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel copyright;
    private javax.swing.JTextField entryTimeField;
    private javax.swing.JLabel entryTimeLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField exitTimeField;
    private javax.swing.JLabel exitTimeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField licensePlateField;
    private javax.swing.JLabel licensePlateLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JLabel totalValue;
    // End of variables declaration//GEN-END:variables
}
