/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parking.view;

import parking.classes.DatesTime;
import parking.classes.Car;
import parking.classes.Motorcycle;
import parking.classes.Truck;
import parking.classes.Vehicle;
import parking.classes.VehicleType;
import parking.service.ParkingService;

import javax.swing.*;
import java.util.Objects;

/**
 * Nama             : Raissa Christabel Sebayang - 140810240008
 *                    Abraham Gomes Samosir - 140810240044
 *                    Haris Herdiansyah - 140810240074
 * Program Utama    : Aplikasi Parkir Pelabuhan
 * Modul            : ParkingFrame.java
 * Deskripsi        : Frame utama aplikasi parkir pelabuhan
 * Tanggal          : 11 November 2025
 */
public class ParkingFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParkingFrame.class.getName());
    private final ParkingService parkingService = new ParkingService();

    /**
     * Creates new form ParkingFrame
     */
    public ParkingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPanel = new javax.swing.JPanel();
        borderPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOutput = new javax.swing.JTextArea();
        licensePlateLabel = new javax.swing.JLabel();
        licensePlateField = new javax.swing.JTextField();
        vehicleTypeLabel = new javax.swing.JLabel();
        vehicleTypeComboBox = new javax.swing.JComboBox<>();
        formatInfo = new javax.swing.JLabel();
        entryTimeLabel = new javax.swing.JLabel();
        entryTimeField = new javax.swing.JTextField();
        exitTimeLabel = new javax.swing.JLabel();
        exitTimeField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        totalValue = new javax.swing.JLabel();
        terminateBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        borderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parkir Pelabuhan"));

        areaOutput.setColumns(20);
        areaOutput.setRows(5);
        areaOutput.setText("No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tSelisih Waktu\t\tBiaya Parkir");
        jScrollPane1.setViewportView(areaOutput);

        licensePlateLabel.setText("No. Plat");

        licensePlateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                licensePlateFieldKeyPressed(evt);
            }
        });

        vehicleTypeLabel.setText("Tipe");

        vehicleTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Mobil", "Motor", "Truk" }));
        vehicleTypeComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vehicleTypeComboBoxKeyPressed(evt);
            }
        });

        formatInfo.setText("Format waktu: yyyy/MM/dd HH:mm:ss");

        entryTimeLabel.setText("Waktu Masuk");

        entryTimeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entryTimeFieldKeyPressed(evt);
            }
        });

        exitTimeLabel.setText("Waktu Keluar");

        exitTimeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exitTimeFieldKeyPressed(evt);
            }
        });

        addButton.setMnemonic('t');
        addButton.setText("Tambah");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addButtonKeyPressed(evt);
            }
        });

        totalLabel.setText("Total :");

        totalValue.setText("Rp0,00");

        terminateBtn.setMnemonic('k');
        terminateBtn.setText("Keluar");
        terminateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminateBtnActionPerformed(evt);
            }
        });

        resetBtn.setMnemonic('r');
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borderPanelLayout = new javax.swing.GroupLayout(borderPanel);
        borderPanel.setLayout(borderPanelLayout);
        borderPanelLayout.setHorizontalGroup(
            borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(borderPanelLayout.createSequentialGroup()
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(borderPanelLayout.createSequentialGroup()
                                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(vehicleTypeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(licensePlateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(licensePlateField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(vehicleTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(formatInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                        .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(borderPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(borderPanelLayout.createSequentialGroup()
                                        .addComponent(exitTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(exitTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(borderPanelLayout.createSequentialGroup()
                                        .addComponent(entryTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(entryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(borderPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addButton))))
                    .addGroup(borderPanelLayout.createSequentialGroup()
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn)
                        .addGap(18, 18, 18)
                        .addComponent(terminateBtn)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        borderPanelLayout.setVerticalGroup(
            borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlateLabel)
                    .addComponent(licensePlateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entryTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleTypeLabel)
                    .addComponent(exitTimeLabel)
                    .addComponent(exitTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formatInfo)
                    .addComponent(addButton))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(borderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalValue)
                    .addComponent(terminateBtn)
                    .addComponent(resetBtn))
                .addContainerGap())
        );

        jLabel1.setText("Copyright @ Raissa (08) - Abraham (44) - Haris (74)");

        javax.swing.GroupLayout rootPanelLayout = new javax.swing.GroupLayout(rootPanel);
        rootPanel.setLayout(rootPanelLayout);
        rootPanelLayout.setHorizontalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        rootPanelLayout.setVerticalGroup(
            rootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(borderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetFieldAction() {
        licensePlateField.setText("");
        entryTimeField.setText("");
        exitTimeField.setText("");
        vehicleTypeComboBox.setSelectedIndex(0);
    }

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here
        resetFieldAction();
        areaOutput.setText("");
        totalValue.setText("Rp0,00");
        parkingService.getVehicleList().clear();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void terminateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminateBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_terminateBtnActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        try {
            String licensePlate = licensePlateField.getText();
            DatesTime entryTime = parkingService.datesTimeParser(entryTimeField.getText());
            DatesTime exitTime = parkingService.datesTimeParser(exitTimeField.getText());
            String vehicleTypeStr = switch ((String) Objects.requireNonNull(vehicleTypeComboBox.getSelectedItem())) {
                case "Mobil" -> "CAR";
                case "Motor" -> "MOTORCYCLE";
                case "Truk" -> "TRUCK";
                default -> throw new IllegalArgumentException("Tipe kendaraan tidak valid.");
            };
            VehicleType vehicleType = VehicleType.valueOf(vehicleTypeStr);

            Vehicle obj = switch (vehicleType) {
                case CAR -> new Car(licensePlate, entryTime, exitTime);
                case MOTORCYCLE -> new Motorcycle(licensePlate, entryTime, exitTime);
                case TRUCK -> new Truck(licensePlate, entryTime, exitTime);
            };

            parkingService.addVehicle(obj);

            String areaOutputHeader = "No. Plat\tTipe\tWaktu Masuk\t\tWaktu Keluar\t\tSelisih Waktu\t\tBiaya Parkir";
            areaOutput.setText("");
            areaOutput.setText(areaOutputHeader.concat(parkingService.getMappedVehicleList()));
            totalValue.setText("Rp" + String.format("%,.2f", parkingService.calculateTotalRevenue()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            resetFieldAction();
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void licensePlateFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_licensePlateFieldKeyPressed
        if(evt.getKeyCode() == 0x0A){
            vehicleTypeComboBox.requestFocus();
        }
    }//GEN-LAST:event_licensePlateFieldKeyPressed

    private void vehicleTypeComboBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vehicleTypeComboBoxKeyPressed
        if(evt.getKeyCode() == 0x0A){
            entryTimeField.requestFocus();
        }
    }//GEN-LAST:event_vehicleTypeComboBoxKeyPressed

    private void entryTimeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entryTimeFieldKeyPressed
        if(evt.getKeyCode() == 0x0A){
            exitTimeField.requestFocus();
        }
    }//GEN-LAST:event_entryTimeFieldKeyPressed

    private void exitTimeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exitTimeFieldKeyPressed
        if(evt.getKeyCode() == 0x0A){
            addButton.requestFocus();
        }
    }//GEN-LAST:event_exitTimeFieldKeyPressed

    private void addButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyPressed
        
    }//GEN-LAST:event_addButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ParkingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea areaOutput;
    private javax.swing.JPanel borderPanel;
    private javax.swing.JTextField entryTimeField;
    private javax.swing.JLabel entryTimeLabel;
    private javax.swing.JTextField exitTimeField;
    private javax.swing.JLabel exitTimeLabel;
    private javax.swing.JLabel formatInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField licensePlateField;
    private javax.swing.JLabel licensePlateLabel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel rootPanel;
    private javax.swing.JButton terminateBtn;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalValue;
    private javax.swing.JComboBox<String> vehicleTypeComboBox;
    private javax.swing.JLabel vehicleTypeLabel;
    // End of variables declaration//GEN-END:variables
}
